
@baseUrl = http://{{$dotenv HOST}}:{{$dotenv PORT}}
@tenantId = {{$dotenv LOCAL_TENANT_ID}}
@contentType = application/json

# @name loginTenant
POST {{baseUrl}}/auth/signin/tenant
Content-Type: {{contentType}}

{
  "key": "{{$dotenv LOCAL_AUTH_KEY}}",
  "secret": "{{$dotenv LOCAL_AUTH_SECRET}}",
  "tenantId": "{{tenantId}}"
}

###

@authToken = {{loginTenant.response.body.token}}
@refreshToken = {{loginTenant.response.body.refreshToken}}

# @name findUserByEmail
GET {{baseUrl}}/users/find-user-by-email?email=usera%2B6%40example.com&tenantId={{tenantId}}
Content-Type: {{contentType}}
accept: application/json
Authorization: Bearer {{authToken}}
