
@baseUrl = http://{{$dotenv HOST}}:{{$dotenv PORT}}
@tenantId = {{$dotenv LOCAL_TENANT_ID}}
@contentType = application/json

# @name login
POST {{baseUrl}}/auth/signin
Content-Type: {{contentType}}

{
  "email": "{{$dotenv LOCAL_AUTH_EMAIL}}",
  "password": "{{$dotenv LOCAL_AUTH_PASS}}",
  "tenantId": "{{tenantId}}"
}

###

# @name logout
POST {{baseUrl}}/auth/logout
Content-Type: {{contentType}}
accept: application/json
Authorization: Bearer {{authToken}}

###

@authToken = {{login.response.body.token}}
@refreshToken = {{login.response.body.refreshToken}}

# @name get-user-profile
GET {{baseUrl}}/users/profile
Content-Type: {{contentType}}
accept: application/json
Authorization: Bearer {{authToken}}

###

# @name get-jwks
GET {{baseUrl}}/auth/jwks.json
Content-Type: {{contentType}}
accept: application/json

###

@verificationToken = "db2099dbd6319b1317492459e2b67f1fce0b96d116fcee5f72591644c151b70d;1657308598033"

# @name reset-password
POST {{baseUrl}}/auth/reset-password
Content-Type: {{contentType}}

{
  "email": "tropix@mailinator.com",
  "token": {{verificationToken}},
  "password": "P@ssw0rd",
  "confirmation": "P@ssw0rd"
}

###

@authToken = {{login.response.body.token}}
@refreshToken = {{login.response.body.refreshToken}}

# @name refresh-token
POST {{baseUrl}}/auth/refresh-token
Content-Type: {{contentType}}
accept: application/json
Authorization: Bearer {{authToken}}

{
  "refreshToken": "{{refreshToken}}"
}

###

# @name login
POST {{baseUrl}}/auth/signin/tenant
Content-Type: {{contentType}}

{
  "key": "{{$dotenv LOCAL_AUTH_KEY}}",
  "secret": "{{$dotenv LOCAL_AUTH_SECRET}}",
  "tenantId": "{{$dotenv LOCAL_AUTH_ID}}"
}

###

# @name signup
POST {{baseUrl}}/auth/signup
Content-Type: {{contentType}}

{
  "email": "{{$dotenv LOCAL_AUTH_EMAIL}}",
  "password": "{{$dotenv LOCAL_AUTH_PASS}}",
  "confirmation": "{{$dotenv LOCAL_AUTH_PASS}}",
  "tenantId": "{{tenantId}}",
  "name": "Jon Doe",
  "i18nLocale": "pt-br",
  "callbackUrl": "http://localhost:3000/signup"
}

###
