name: Create Release Branch

on:
  workflow_dispatch:
  schedule:
    # Every friday at midnight
    - cron: "0 23 * * FRI"

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Initialize git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      
      - name: Create release branch
        run: git checkout -b release/${{ steps.date.outputs.date }}

      - name: Push new branch
        run: git push origin release/${{ steps.date.outputs.date }}
